import { collections } from "@/src/lib/db/mongodb";
import { ok,fail,resolveOwner,toObjectId } from "@/src/lib/server-utils";
import { validateAddress,firstError } from "@/src/lib/validation";
function filter(owner){return owner.userId?{$or:[{userId:toObjectId(owner.userId)},{user_id:String(owner.userId)}]}:{$or:[{guestId:owner.guestId},{guest_id:owner.guestId}]}}
const serialize=a=>({...a,_id:String(a._id),userId:a.userId?String(a.userId):(a.user_id||null),guestId:a.guestId||a.guest_id||null,is_selected:Boolean(a.is_selected??a.isSelected),address:a.street_address});
export async function GET(req){try{const owner=await resolveOwner(req.nextUrl.searchParams.get("guest_id"));if(!owner.userId&&!owner.guestId)return ok([]);const list=await(await collections.addresses()).find(filter(owner)).sort({is_selected:-1,updated_at:-1,created_at:-1}).toArray();return ok(list.map(serialize));}catch(e){console.error(e);return fail("Could not load addresses.",500)}}
export async function POST(req){try{const b=await req.json(),owner=await resolveOwner(b.guest_id);if(!owner.userId&&!owner.guestId)return fail("Please verify your mobile number first.",401);const a={name:String(b.name||"").trim(),street_address:String(b.street_address||b.address||"").trim(),city:String(b.city||"").trim(),state:String(b.state||"").trim(),pincode:String(b.pincode||"").trim(),phone:String(b.phone||"").replace(/\D/g,"").slice(-10)};const errors=validateAddress(a);if(Object.keys(errors).length)return fail(firstError(errors));const c=await collections.addresses(),now=new Date();const count=await c.countDocuments(filter(owner));const doc={...a,userId:owner.userId?toObjectId(owner.userId):null,user_id:owner.userId?String(owner.userId):null,guestId:owner.guestId,guest_id:owner.guestId,is_selected:count===0,isSelected:count===0,created_at:now,createdAt:now,updated_at:now,updatedAt:now};const r=await c.insertOne(doc);return ok(serialize({...doc,_id:r.insertedId}));}catch(e){console.error(e);return fail("Could not save address.",500)}}
export async function PATCH(req){try{const b=await req.json(),id=toObjectId(b.id||b.address_id),owner=await resolveOwner(b.guest_id);if(!id)return fail("Invalid address.");const c=await collections.addresses(),existing=await c.findOne({_id:id,...filter(owner)});if(!existing)return fail("Address not found.",404);const a={name:String(b.name??existing.name).trim(),street_address:String(b.street_address??b.address??existing.street_address).trim(),city:String(b.city??existing.city).trim(),state:String(b.state??existing.state).trim(),pincode:String(b.pincode??existing.pincode).trim(),phone:String(b.phone??existing.phone).replace(/\D/g,"").slice(-10)};const errors=validateAddress(a);if(Object.keys(errors).length)return fail(firstError(errors));await c.updateOne({_id:id},{$set:{...a,updated_at:new Date(),updatedAt:new Date()}});return ok({updated:true});}catch(e){console.error(e);return fail("Could not update address.",400)}}
export async function DELETE(req){try{const b=await req.json(),id=toObjectId(b.id||b.address_id),owner=await resolveOwner(b.guest_id);if(!id)return fail("Invalid address.");const c=await collections.addresses();const current=await c.findOne({_id:id,...filter(owner)});if(!current)return fail("Address not found.",404);await c.deleteOne({_id:id});if(current.is_selected||current.isSelected){const next=await c.findOne(filter(owner),{sort:{updated_at:-1,created_at:-1}});if(next)await c.updateOne({_id:next._id},{$set:{is_selected:true,isSelected:true}})}return ok({deleted:true});}catch(e){console.error(e);return fail("Could not delete address.",400)}}
