"use client";
import {useEffect,useState} from "react";import {useRouter,useSearchParams} from "next/navigation";import AddressSection from "./address-section";import PaymentSection from "./payment-section";import OrderSummary from "./order-summary";import ModalHeadlessUi from "../modal/headless-ui-modal";import AddressForm from "../modal/address-form";import OtpLoginModal from "../auth/otp-login";import {getAddresses,addGuestAddress,selectGuestAddress,order} from "@/src/lib/api";
const getGuestId=()=>{let id=localStorage.getItem('guest_id');if(!id){id=crypto.randomUUID();localStorage.setItem('guest_id',id)}return id};
export default function CheckoutPage(){const router=useRouter(),sp=useSearchParams(),checkoutId=sp.get('checkout');const[addresses,setAddresses]=useState([]),[selectedAddressId,setSelectedAddressId]=useState(null),[showAddressModal,setShowAddressModal]=useState(false),[showLoginModal,setShowLoginModal]=useState(false),[loading,setLoading]=useState(false),[paymentPlan,setPaymentPlan]=useState('cod'),[isLoggedIn,setIsLoggedIn]=useState(null),[error,setError]=useState('');const step=sp.get('step')||(isLoggedIn?'address':'verify');
 async function refreshAuth(){const j=await fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.json()).catch(()=>({}));const logged=Boolean((j.data||j).loggedIn);setIsLoggedIn(logged);return logged}
 async function loadAddresses(){const data=await getAddresses({guest_id:getGuestId()});const selected=data.find(a=>a.is_selected||a.isSelected)?._id||data[0]?._id||null;setAddresses(data.map(a=>({...a,is_selected:a._id===selected})));setSelectedAddressId(selected)}
 useEffect(()=>{refreshAuth().then(logged=>{loadAddresses();if(logged&&sp.get('step')==='verify')go('address')})},[]);
 function go(s){router.push(`/checkout?checkout=${encodeURIComponent(checkoutId||'')}&step=${s}`)}
 function continueAddress(){setError('');if(!selectedAddressId){setError('Select or add a delivery address to continue.');return}go('payment')}
 async function otpDone(){setShowLoginModal(false);setIsLoggedIn(true);await loadAddresses();go('address')}
 async function place(){try{setError('');if(!isLoggedIn){setShowLoginModal(true);return}setLoading(true);const d=await order({checkoutId,paymentPlan});window.location.replace(`/order-success?order_id=${d.order_id}`)}catch(e){setError(e.message||'Could not place order. Please try again.');setLoading(false)}}
 async function select(id){try{await selectGuestAddress({address_id:id,guest_id:getGuestId()});const a=addresses.find(x=>x._id===id);if(a&&checkoutId)await fetch('/api/checkouts',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:checkoutId,address:a})});setSelectedAddressId(id);setAddresses(p=>p.map(a=>({...a,is_selected:a._id===id})))}catch{setError('Could not select address.')}}
 async function save(a){try{const saved=await addGuestAddress({...a,guest_id:getGuestId()});setAddresses(p=>[...p.map(x=>({...x,is_selected:false})),{...saved,is_selected:true}]);setSelectedAddressId(saved._id);if(checkoutId)await fetch('/api/checkouts',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:checkoutId,address:saved})});setShowAddressModal(false)}catch(e){setError(e.message||'Could not save address.')}}
 if(isLoggedIn===null)return <main className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-6xl text-sm text-gray-500">Loading secure checkout…</div></main>;
 return <main className="min-h-screen bg-gray-50 px-3 py-4 pb-28 md:px-8 md:py-8"><div className="mx-auto max-w-6xl"><div className="mb-5"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-800">Secure checkout</p><h1 className="text-2xl font-bold text-gray-900">Complete your order</h1></div>{error&&<div className="mb-4 rounded-xl border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{step==='verify'&&!isLoggedIn?<div className="grid gap-5 md:grid-cols-[1fr_380px]"><section className="rounded-2xl bg-white p-5 shadow-sm"><span className="text-xs font-bold text-emerald-800">STEP 1 OF 3</span><h2 className="mt-2 text-xl font-semibold">Verify your mobile number</h2><p className="mt-2 max-w-lg text-sm leading-6 text-gray-600">Verify once to save this checkout to your account. If you complete the order later, it will automatically appear in My Orders.</p><button onClick={()=>setShowLoginModal(true)} className="mt-5 w-full rounded-xl bg-primary py-3.5 font-semibold text-white md:w-auto md:px-8">Continue with mobile</button></section><OrderSummary checkoutId={checkoutId} showButton={false}/></div>:step==='address'?<div className="grid gap-5 md:grid-cols-[1fr_380px]"><div><AddressSection addresses={addresses} selectedAddressId={selectedAddressId} setSelectedAddressId={select} onAddAddress={()=>setShowAddressModal(true)}/><button onClick={continueAddress} className="mt-4 hidden w-full rounded-xl bg-primary py-3.5 font-semibold text-white md:block">Continue to payment</button></div><OrderSummary checkoutId={checkoutId} showButton={false}/><MobileBar label="Continue to payment" onClick={continueAddress}/></div>:<div className="grid gap-5 md:grid-cols-[1fr_380px]"><PaymentSection value={paymentPlan} onChange={setPaymentPlan}/><OrderSummary checkoutId={checkoutId} onPlaceOrder={place} placing={loading}/><MobileBar label={loading?'Placing order…':'Place order'} onClick={place} disabled={loading}/></div>}</div><OtpLoginModal open={showLoginModal} onClose={()=>setShowLoginModal(false)} onSuccess={otpDone}/><ModalHeadlessUi isOpen={showAddressModal} onClose={()=>setShowAddressModal(false)} title="Add delivery address"><AddressForm onClose={()=>setShowAddressModal(false)} handleSaveAddress={save}/></ModalHeadlessUi></main>}
function MobileBar({label,onClick,disabled}){return <div className="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 p-3 backdrop-blur md:hidden"><button disabled={disabled} onClick={onClick} className="w-full rounded-xl bg-primary py-3.5 font-semibold text-white disabled:opacity-50">{label}</button></div>}
